services:
  # 1. Base de Datos integrada (MySQL)
  sanitypet-db:
    image: mysql:8.0
    container_name: sanitypet-db
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: sanitypet
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker-db:/docker-entrypoint-initdb.d
    networks:
      - sanitypet-network
    # 🌟 AQUÍ ESTÁ EL TRUCO: Ahora Docker sí sabrá cuándo está lista la BD
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 10

  # 2. Gestor Web (Interfaz visual)
  phpmyadmin:
    image: phpmyadmin:latest
    container_name: sanitypet-phpmyadmin
    restart: always
    environment:
      PMA_HOST: sanitypet-db
      PMA_USER: root
      PMA_PASSWORD: ""
    ports:
      - "8080:80"
    networks:
      - "sanitypet-network"
    depends_on:
      - sanitypet-db

  # 3. Tu aplicación de Spring Boot
  sanitypet-app:
    build: .
    container_name: sanitypet-app
    restart: always
    ports:
      - "8090:8090"
    networks:
      - sanitypet-network
    depends_on:
      sanitypet-db:
        condition: service_healthy

volumes:
  mysql_data:

networks:
  sanitypet-network: